### ISSUE TITLE
Remove Invite code and expire it from your JSS

### ISSUE THREAD

**Issue by rderewianko** [atscomposer/JAMF_Scripts#1]
Hello!

Posting a computer invite code for your JSS is not a secure thing to do. It opens the doors for external users to access your JSS.

Your script: https://github.com/atscomposer/JAMF_Scripts/blob/master/JAMF_AutoReEnroll/enrollcheck.sh#L35shows an invite code.

What you'll want todo is expire this invite code, by going to the API.

[Your JSS API link is here](https://irbt.jamfcloud.com/api) scroll down to computerinvitations. Do a GET on  invites, and then match the ID to the ID of your invite code. 

The invite code you're looking for is: ****

Then open terminal do a delete request in curl to remove that.

```
## Request
curl -X "DELETE" "https://irbt.jamfcloud.com:8443/JSSResource/computerinvitations/id/<idhere>" \
     -u adminuser:adminpass

```

**Comment by rderewianko** [comment]
You may also want to remove
https://github.com/atscomposer/JAMF_Scripts/blob/master/JAMF_AutoReEnroll/enrollcheck.sh#L23

**Comment by atscomposer** [comment]
Thanks @rderewianko.  I thought I had scrubbed all my code fully but I guess I missed a couple things.  These have been removed.  Thanks again.
